create new circleLayerType and add switch case depend on layer type
orabazu/rabonajs pull request #3
Opened 2022-07-13 11:26 UTC by yasinvural

updated RabonaLayer with new types
added RabonaCircleLayerData
renamed RabonaLayerData to RabonaLineLayerData
* could not use ts properly on addLayer method

2022-07-19 11:05 UTC, orabazu requested changes
@yasinvural thanks ✨,  there are some things related with naming mostly.

2022-07-19 11:05 UTC, orabazu commented on lib/index.js
> +      case "point":
Point was a hypothetical layer to do what you have a already done here. Could you please get rid of it

2022-07-19 11:05 UTC, orabazu commented on src/Layer/Layer.ts
> +export type RabonaLayer = 'line' | 'point' | 'circle' | 'passLayer';
In the existince of circle we wouldn't need point layer here as well

2022-07-19 11:05 UTC, orabazu commented on src/Layer/Layer.ts
> +    public data: RabonaLineLayerData[] | RabonaCircleLayerData,
This is my mistake, circle layer could be array as well. Otherwise we need take care of whole array non-array situations in many places. For the sake of simplicity let's make it array as well. So in this case better to create a RabonaData type which will include everything and use it in other data related fields. 

`type RabonaData: RabonaLineLayerData[] | RabonaCircleLayerData[]`

if you have one data to visualize then passing it like
`data: [{cx,cy,radius}] ` will do

2022-07-19 11:05 UTC, orabazu commented on src/Pitch/Pitch.ts
> +      case 'point':
Again we don't need point here. Could please delete it

2022-07-19 11:05 UTC, orabazu commented on lib/index.js
> +    const temp = layer;
tempLayer could be a better name, switch case could be sort of long in the future and temp is somewhat very generic name. tempLayer would be better to see what you're dealing with at the first glance imo. But it is still the same reference, do we really need that temp variable?

2022-07-19 11:05 UTC, orabazu commented on lib/index.cjs
> +      case "point":
Let's remove point from here as well. My bad 🤷‍♂️

2022-07-19 11:05 UTC, orabazu commented on lib/Layer/Layer.d.ts
> +    data: RabonaLineLayerData[] | RabonaCircleLayerData;
The `RabonaData` type that I mentioned above could be used here as well

2022-07-19 11:05 UTC, orabazu commented on lib/Layer/Layer.d.ts
> +export declare type RabonaLayer = 'line' | 'point' | 'circle' | 'passLayer';
As we have circle we won't need point layer. Could please remove?

2022-07-21 17:58 UTC, yasinvural commented
@orabazu removed the 'point' from all place. While adding new layer, in switch case statement, I was using the layer type as RabonaCircleLayerData | RabonaLineLayerData. However because our new type, passLayer is similar to RabonaLineLayerData but just for the sake of readability I also added RabonaPassLayerData.
if it does not make sense for you, we can discuss

2022-07-21 21:49 UTC, orabazu commented
@yasinvural from TS standpoint the new type is `layer` here not the data field inside of layer. So data could be lineLayer or something i would say. No need to define a specific type for a sub field like this. Other than that LGTM ✅

2022-07-21 21:49 UTC, orabazu approved these changes

2022-07-22 20:47 UTC, merged